# -*- coding: utf-8 -*-
"""NLP_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iYi6CKioj48E6ySNARAd8wv2Mwip7DI
"""

!git clone https://github.com/michiyasunaga/qagnn.git

!pip install -q condacolab

import condacolab
condacolab.install()

!conda -V

!conda create -n qagnn python=3.7
# !conda update -n base -c conda-forge conda
# !source /usr/local/etc/profile.d/conda.sh
# !conda activate qagnn
!source activate qagnn
!pip install torch==1.8.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
!pip install transformers==3.4.0
!pip install nltk spacy==2.1.6
!python -m spacy download en

!pip install torch-scatter==2.0.7 -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
!pip install torch-sparse==0.6.9 -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
!pip install torch-geometric==1.7.0 -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/qagnn
!sh download_preprocessed_data.sh

#!pip3 install transformers
#!pip3 install torch_geometric
#!pip3 install torch_sparse
!chmod u+x qagnn.py

!pip install protobuf==3.20.*

!sh run_qagnn__csqa.sh

!sh eval_qagnn__csqa.sh

